---
- name: Ping Windows Server
  hosts: "{{ destination_host | default('server') }}"
  gather_facts: no
  vars:
    ansible_shell_type: cmd
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_winrm_transport: ntlm
    ansible_winrm_operation_timeout_sec: 60
    ansible_winrm_read_timeout_sec: 70
  tasks:
    - name: Try to ping Windows host
      ansible.windows.win_ping:
      register: ping_result
      ignore_errors: yes
      
    - name: Restart Windows Server if ping failed
      win_reboot:
        msg: "Restarting Windows Server due to failed ping"
        pre_reboot_delay: 5
        post_reboot_delay: 30
        test_command: whoami
      when: ping_result is failed
      
    - name: Show message if server is responsive
      debug:
        msg: "Server is responding to ping, no restart needed"
      when: ping_result is success