---
- name: Ping Windows Server
  hosts: "{{ destination_host | default('server') }}"
  gather_facts: no
  vars:
    ansible_shell_type: cmd
    ansible_connection: winrm
    ansible_winrm_scheme: http
    ansible_winrm_server_cert_validation: ignore
  tasks:
    - name: Ping Windows host
      ansible.windows.win_ping: